#!/bin/bash
echo "============================"
echo "Downloading final scripts..."
echo "============================"
wget https://raw.githubusercontent.com/JoshMiles/SOXS/master/OTHER/prep
cd ..
wget https://raw.githubusercontent.com/JoshMiles/SOXS/master/OTHER/run
wget https://raw.githubusercontent.com/JoshMiles/SOXS/master/OTHER/kbuild
echo "DONE"