#!/bin/bash
# the setup script
# use $ chmod a+x setup to mark it as executable
# then use $ ./setup to run it. Or just use $ bash setup
# Created for Emily's tutorial at int0x10

# Useful functions
function mkd {
	mkdir $1
	echo "Created: $1"
}

# Directory structure setup
clear
echo "====================================="
echo "Setting up the directory structure..."
echo "====================================="
md src
md build
md toolchain
md cross-compiler-setup
cd cross-compiler-setup
md source_code
cd ..
cd toolchain

# Download some useful toolchain scripts

echo "====================================="
echo "Downloading default toolchain scripts...
echo "====================================="
wget https://raw.githubusercontent.com/JoshMiles/SOXS/master/OTHER/rp
wget https://raw.githubusercontent.com/JoshMiles/SOXS/master/OTHER/gcc

# Make the scripts executable

echo "====================================="
echo "Applying chmod...
echo "====================================="
chmod a+x rp
chmod a+x gcc

# Installing dependancies

echo "====================================="
echo "Installing required packages..."
echo "====================================="
bash rp

# Launch the GCC script

echo "====================================="
echo "Finished setup, launching gcc script..."
echo "====================================="
#bash gcc
