#!/bin/bash
# Created for Emily's tutorial at int0x10
# YUM version
sudo yum install wget
sudo yum install gcc-c++
sudo yum install make
sudo yum install bison
sudo yum install flex
sudo yum install gmp
sudo yum install mpfr
sudo you install mpc
echo "DONE"
