#!/bin/sh
set -e

wk_dir=$(mktemp -d "${TMPDIR:-/tmp}/tmp.XXXXXXXXXX")
mkdir -p ${wk_dir}/boot/grub

# copy your /boot/grub/grub.cfg file to the work dir
cp -v /boot/grub2/grub.cfg ${wk_dir}/boot/grub

# run grub-mkrescue should create new image grub.iso in the current dir
grub2-mkrescue --modules="ext2 lvm" -o ./grub.iso ${wk_dir}

rm -rf ${wk_dir}
